### ISSUE TITLE
What does suffix colon `:` mean in query?

### ISSUE THREAD

**Issue by snowman** [hasu/notdeft#16]
![](https://tero.hasu.is/notdeft/directory-indicator.png)

- `!all title:"programming language": cross plat`
- `!rank qt:` or `!rank emacs:`
- `racket scheme lisp:`

**Comment by snowman** [comment]
Does it literally match `:`?

**Comment by hasu** [comment]
In the picture the `:` is not a part of the query, it's just used as a 
separator between the query and the filter string in the UI.

What it does in a query is really a Xapian query parser question, but at 
the end of a query it makes no difference as far as I know. As a word 
separator it appears to produce a phrase.
