### ISSUE TITLE
notdeft-parse-buffer gets confused with a PROPERTIES drawer at the top of org file

### ISSUE THREAD

**Issue by harizvi** [hasu/notdeft#19]
Org files can have a properties drawer at the top of the file. See https://orgmode.org/manual/Property-Syntax.html

notdeft-parse-buffer doesn't handle it correctly right now. I added the following regexp which works on my files.

```
       ((looking-at "^\\(?:%\\|@;\\|<!--\\)?[[:blank:]]*:[[:graph:]]+:.*$") ;; ignore PROPERTIES drawer
        (goto-char (match-end 0)))

```

If you agree, please fix. Org-roam v2 will use org ids for linking, and they go in the top properties drawer.

**Comment by hasu** [comment]
Thank you for letting me know. I wasn't aware that such syntax is now 
supported by Org.

I would agree that it's then probably necessary for NotDeft also to have 
some support for that syntax to keep things usable if such a drawer 
appears at the top of each note.

I've pushed such support to a `devel'opment branch. Note that there's a 
configuration option for enabling the syntax extension.

**Comment by harizvi** [comment]
Thanks for the update. 

Official regexp for properties drawer is at org.el::564, which suggests that whitespace ahead of :PROPERTIES: is acceptable even at the start of the doc. I think your new code doesn't deal with that right now. 

```
(defconst org-property-drawer-re
  (concat "^[ \t]*:PROPERTIES:[ \t]*\n"
	  "\\(?:[ \t]*:\\S-+:\\(?: .*\\)?[ \t]*\n\\)*?"
	  "[ \t]*:END:[ \t]*$")
  "Matches an entire property drawer.")
```

**Comment by hasu** [comment]
It didn't, and I've pushed another change to allow the whitespace. 
Hopefully now the syntax is reasonably compatible with Org, and also 
consistent between the C++ and Emacs Lisp implementations.

**Comment by harizvi** [comment]
Looks good. Thanks for addressing this issue.
