### ISSUE TITLE
attempt to index fails with "is a directory" error

### ISSUE THREAD

**Issue by emacsomancer** [hasu/notdeft#20]
Attempt to index is now failing with an "is a directory" error; I suspect it's something about the file-name (auto-generated by `org-download-image`):

````
notdeft-cache-newer-file: Read error: Is a directory, /home/emacsomancer/Documents/Org/org-roam/daily/[[file:../20210410085803-walnut_ink.org][walnut_ink]]_lightfastness_test_-_[[https:/web.archive.org [4 times]
````

No similar issue when using Deft.

**Comment by hasu** [comment]
The reported directory name looks strange. What is the actual full 
filesystem path name of the downloaded image?

One possible cause for "Is a directory" errors is that the current 
notdeft-xapian implementation assumes that there are no note 
subdirectories whose name ends in `notdeft-extension' or one of the 
`notdeft-secondary-extensions'. If that assumption doesn't hold then 
directory names could end up in the search index, causing errors such as 
the one you're seeing (when attempting to `insert-file-contents').

**Comment by emacsomancer** [comment]
as reported by dired:

`/home/emacsomancer/Documents/Org/org-roam/daily/[[file:../20210410085803-walnut_ink.org][walnut_ink]]_lightfastness_test_-_[[https:/web.archive.org/web/20110310183344/http:/www.wetcanvas.com/forums/showthread.php?t=523004][Walnut_ink_lightfastness_test_and_some_drawings_-_WetCanvas]]/2021-04-12_20-03-42_DSC01664.JPG`

(It is strange, but the sort of thing that `org-download-image` tends to end up producing.)

I actually don't need notdeft looking in these sorts of 'weird' directories as they're always just going to have image files in them (rather than .org files), but I'm not sure how I would programmatically exclude them.

**Comment by hasu** [comment]
Interesting, as not all file systems even allow slashes in file name 
components, but that seems to be the case here. No wonder if 
notdeft-xapian gets confused.

You might indeed try modifying the program to exclude such names, where 
it uses `readdir`. Perhaps just something like

     if (!(string_starts_with(name, ".")
	  || string_starts_with(name, "_")
	  || string_starts_with(name, "#"))
	&& (name.find('/') == string::npos)) {
       lst.push_back(name);
     }

**Comment by hasu** [comment]
I pushed the change e28bf5a some time ago to exclude files whose names contain slashes from being considered as notes, roughly as suggested above. That then should prevent the described problem from occurring, although I haven't tested the change to confirm that it works as intended. The ticket can be reopened as appropriate.
