### ISSUE TITLE
display org file title instead of first line of the file. 

### ISSUE THREAD

**Issue by CsBigDataHub** [hasu/notdeft#21]
hey @hasu 

Is it possible to display title of the org-file instead of first line of the file when `notdeft` is called.

display buffer when `M-x deft` is called
![image](https://user-images.githubusercontent.com/23665525/126197774-46ab4363-7ea5-4811-b1bd-99e935c38bf4.png)

display buffer when `M-x notdeft` is called
![image](https://user-images.githubusercontent.com/23665525/126197829-046a184e-6fe0-4c21-8a7e-e29713b9f29f.png)

deft used `deft-strip-title-regexp` variable to strip title from the org-file and display it in `deft` buffer. 
If `#+TITLE:` or `#+title:` is not present in the file, `file name` is used.

Is it possible to do that in `notdeft` ?

**Comment by hasu** [comment]
In general, no. The `deft-strip-title-regexp' mechanism was never 
present in NotDeft, and NotDeft also only parses the beginning of each 
file, meaning that a recognized #+title cannot appear just anywhere.

However, looking at your screenshot, it seems that in your case it is 
the property drawers that are the issue, and there is specific support 
for ignoring those at the very beginning of a file. See if it helps to

   (setq notdeft-allow-org-property-drawers t)

**Comment by CsBigDataHub** [comment]
Awesome, thanks that worked.
