### ISSUE TITLE
Ignore PROPERTIES display in title.

### ISSUE THREAD

**Issue by GTrunSec** [hasu/notdeft#22]
This PR request is related to Roam v2. 

- to creat an org-id for org file such as
![image](https://user-images.githubusercontent.com/21156405/127212221-36293d34-e740-4b3b-a23c-c557b9f34518.png)

- issue by 
![image](https://user-images.githubusercontent.com/21156405/127212136-b7843a16-597e-4268-aeae-8267abf1f11b.png)

**Comment by wohanley** [comment]
`(setq notdeft-allow-org-property-drawers t)` can fix this problem: https://github.com/hasu/notdeft/issues/21#issuecomment-883006414

**Comment by GTrunSec** [comment]
thanks
