### ISSUE TITLE
Unable to clear the notdeft filter after query using TAB

### ISSUE THREAD

**Issue by kaushalmodi** [hasu/notdeft#3]
1. In initiate a query after hitting `TAB`, like `title:sed`. 
2. It works, and shows the filtered notes with the title "sed".
3. But then I am unable to clear that query.. example, `C-c C-c` does not work.

I get this:

![image](https://user-images.githubusercontent.com/3578197/39633453-09fbc688-4f86-11e8-8536-113da22c62bf.png)

If I try to manually delete the "title:sed:" portion, it gives an error saying that the buffer is read-only.. looks like that filter string is made non-editable?

For now, the only option that I have, it seems, is to kill that \*NotDeft\* buffer.

**Comment by hasu** [comment]
Not sure if these are documented at all, but to clear a query, you can

1.  press `TAB` and enter the empty string, or
2.  press `S-TAB`, or
3.  `C-u C-c C-c` also works for clearing the query in addition to any
filter string.

I'll look at improving the docs on this query-then-filter modality and
the relevant keybindings.

Yes, the `*NotDeft*` buffer is read only, and cannot be edited directly,
although as in Deft, most keys without modifiers do cause editing of the
filter string.

**Comment by kaushalmodi** [comment]
> `C-u C-c C-c` also works for clearing the query in addition to any filter string.

Thanks! `C-u C-c C-c` works.. But is there a reason `C-c C-c` is not designed to reset the query?

**Comment by kaushalmodi** [comment]
Thank you for that explanation :+1. It makes sense.
