### ISSUE TITLE
default query

### ISSUE THREAD

**Issue by dppdppd** [hasu/notdeft#30]
Is it possible to specify a default query, e.g. "path:misc?"

**Comment by hasu** [comment]
It should be OK to

  (setq notdeft-xapian-query "path:misc")

to change the initial value. Or do you mean something else?

**Comment by dppdppd** [comment]
Nope. That’s it. Thanks!

**Comment by hasu** [comment]
It should be OK to

   (setq notdeft-xapian-query "path:misc")

to change the initial value. Or do you mean something else?
