### ISSUE TITLE
autosave after editing file in notdeft buffer

### ISSUE THREAD

**Issue by anthrolisp** [hasu/notdeft#7]
Is there any way to autosave an edited file from the notdeft buffer? Deft does this by default. Many thanks in advance!

**Comment by hasu** [comment]
That feature has not been retained from Deft, and I'm not convinced such 
support is needed in NotDeft itself.

Emacs has long had auto-saving of backup files, and I believe more 
recent Emacs versions also include `auto-save-visited-mode', which might 
do what you want if enabled for all files for which `notdeft-note-mode' 
is enabled. I haven't tried that, though.

**Comment by anthrolisp** [comment]
Thank you!
